# -*- coding: utf-8 -*-
"""görüntülü işleme

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1snSBWUjB9haVHnpnSA1xm265FZEMcBkT
"""

!kaggle datasets download -d puneet6060/intel-image-classification
!unzip intel-image-classification.zip

import os
os.listdir('/content')

import os
train_path = '/content/seg_train/seg_train'
classes = os.listdir(train_path)
print(classes)

import os
train_path = '/content/seg_train/seg_train'
classes = os.listdir(train_path)
print(classes)

import cv2
import matplotlib.pyplot as plt
import glob
img_path = glob.glob(train_path + '/buildings/*.jpg')[0]
img = cv2.imread(img_path)
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
plt.imshow(img)
plt.axis('off')
plt.show()

import random
import matplotlib.pyplot as plt
import cv2
import glob
plt.figure(figsize=(12, 8))
for i, class_name in enumerate(classes):
 image_paths = glob.glob(train_path + '/' + class_name + '/*.jpg')
 img_path = random.choice(image_paths)

 img = cv2.imread(img_path)
 img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

 plt.subplot(2, 3, i + 1)
 plt.imshow(img)
 plt.title(class_name)
 plt.axis('off')

plt.show()

import numpy as np
import cv2
import glob
import os

IMG_SIZE = 64
X = []
y = []
for label, class_name in enumerate(classes):
    image_paths = glob.glob(train_path + '/' + class_name + '/*.jpg')

    image_paths = image_paths[:200]

for path in image_paths:

    img = cv2.imread(path)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))

    X.append(img)
    y.append(label)
X = np.array(X)
y = np.array(y)
print("X shape:", X.shape)
print("y shape:", y.shape)

plt.figure(figsize=(4,4))
plt.imshow(X[0])
plt.title(classes[y[0]])
plt.axis('off')
plt.show()

X = X / 255.0
print(X.min())
print(X.max())

sample_img = X[0]
plt.imshow(sample_img)
plt.title("Orijinal Görüntü")
plt.axis("off")
plt.show()

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
datagen = ImageDataGenerator(
rotation_range=30,
width_shift_range=0.2,
height_shift_range=0.2,
zoom_range=0.2,
horizontal_flip=True,
brightness_range=[0.7, 1.3]
)

import numpy as np
import cv2
import matplotlib.pyplot as plt

img = (X[0] * 255).astype(np.uint8)

flip_img = cv2.flip(img, 1)

h, w = img.shape[:2]
M = cv2.getRotationMatrix2D((w//2, h//2), 20, 1)
rotated_img = cv2.warpAffine(img, M, (w, h), borderMode=cv2.BORDER_REFLECT)

bright_img = cv2.convertScaleAbs(img, alpha=1.0, beta=40)

noise = np.random.normal(0, 15, img.shape).astype(np.int16)
noise_img = np.clip(img.astype(np.int16) + noise, 0, 255).astype(np.uint8)

zoom_img = img[8:56, 8:56]
zoom_img = cv2.resize(zoom_img, (64, 64))
images = [img, flip_img, rotated_img, bright_img, noise_img, zoom_img]
titles = ["Orijinal", "Yatay Çevirme", "Döndürme", "Parlaklık", "Gürültü", "Zoom"]

plt.figure(figsize=(12, 8))

for i in range(6):
    plt.subplot(2, 3, i + 1)
    plt.imshow(images[i])
    plt.title(titles[i])
    plt.axis("off")

plt.show()

X_flat = X.reshape(X.shape[0], -1)
print("Orijinal X shape:", X.shape)
print("Flatten sonrası:", X_flat.shape)

from sklearn.decomposition import PCA
pca = PCA(n_components=50)
X_pca = pca.fit_transform(X_flat)
print("PCA sonrası shape:", X_pca.shape)

explained_variance = pca.explained_variance_ratio_.sum()
print("Korunan bilgi oranı:", explained_variance)

plt.figure(figsize=(8, 5))
plt.plot(np.cumsum(pca.explained_variance_ratio_))
plt.xlabel("Bileşen Sayısı")
plt.ylabel("Kümülatif Açıklanan Varyans")
plt.title("PCA - Açıklanan Varyans Grafiği")
plt.grid()
plt.show()

from sklearn.manifold import TSNE
tsne = TSNE(
n_components=2,
perplexity=30,
random_state=42
)
X_tsne = tsne.fit_transform(X_pca)
print("t-SNE sonrası shape:", X_tsne.shape)

plt.figure(figsize=(10, 7))
for label, class_name in enumerate(classes):
    indices = y == label
    plt.scatter(
        X_tsne[indices, 0],
        X_tsne[indices, 1],
        label=class_name,
        alpha=0.7
    )
plt.title("t-SNE ile Görüntü Veri Seti Görselleştirme")
plt.xlabel("t-SNE 1")
plt.ylabel("t-SNE 2")
plt.legend()
plt.grid()
plt.show()

img = (X[0] * 255).astype(np.uint8)
gray_img = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
plt.imshow(gray_img, cmap="gray")
plt.title("Gri Görüntü")
plt.axis("off")
plt.show()
print(gray_img.shape)

kernel = np.array([
[-1, -1, -1],
[-1,  8, -1],
[-1, -1, -1]
])
print(kernel)

conv_img = cv2.filter2D(gray_img, -1, kernel)
plt.figure(figsize=(10, 4))
plt.subplot(1, 2, 1)
plt.imshow(gray_img, cmap="gray")
plt.title("Orijinal Gri Görüntü")
plt.axis("off")
plt.subplot(1, 2, 2)
plt.imshow(conv_img, cmap="gray")
plt.title("Konvolüsyon Sonucu - Kenar Bulma")
plt.axis("off")
plt.show()

blur_kernel = np.ones((5, 5), np.float32) / 25
blur_img = cv2.filter2D(gray_img, -1, blur_kernel)
plt.figure(figsize=(10, 4))
plt.subplot(1, 2, 1)
plt.imshow(gray_img, cmap="gray")
plt.title("Orijinal")
plt.axis("off")
plt.subplot(1, 2, 2)
plt.imshow(blur_img, cmap="gray")
plt.title("Bulanıklaştırma")
plt.axis("off")
plt.show()

sharpen_kernel = np.array([
[ 0, -1,  0],
[-1,  5, -1],
[ 0, -1,  0]
])
sharp_img = cv2.filter2D(gray_img, -1, sharpen_kernel)
plt.imshow(sharp_img, cmap="gray")
plt.title("Keskinleştirme Filtresi")
plt.axis("off")
plt.show()

sobel_x = cv2.Sobel(gray_img, cv2.CV_64F, 1, 0, ksize=3)
sobel_x = np.abs(sobel_x)
plt.imshow(sobel_x, cmap="gray")
plt.title("Sobel X - Dikey Kenarlar")
plt.axis("off")
plt.show()

sobel_y = cv2.Sobel(gray_img, cv2.CV_64F, 0, 1, ksize=3)
sobel_y = np.abs(sobel_y)
plt.imshow(sobel_y, cmap="gray")
plt.title("Sobel Y - Yatay Kenarlar")
plt.axis("off")
plt.show()

canny_img = cv2.Canny(gray_img, 100, 200)
plt.imshow(canny_img, cmap="gray")
plt.title("Canny Kenar Algılama")
plt.axis("off")
plt.show()

gaussian = cv2.GaussianBlur(gray_img, (5,5), 0)
plt.imshow(gaussian, cmap="gray")
plt.title("Gaussian Blur")
plt.axis("off")
plt.show()

median = cv2.medianBlur(gray_img, 5)
plt.imshow(median, cmap="gray")
plt.title("Median Blur")
plt.axis("off")
plt.show()

lap = cv2.Laplacian(gray_img, cv2.CV_64F)
lap = np.absolute(lap)
lap = np.uint8(lap)
plt.imshow(lap, cmap="gray")
plt.title("Laplacian")
plt.axis("off")
plt.show()

plt.figure(figsize=(8,5))
plt.hist(gray_img.ravel(), bins=256)
plt.title("Görüntü Histogramı")
plt.xlabel("Piksel Değeri")
plt.ylabel("Piksel Sayısı")
plt.show()

equalized = cv2.equalizeHist(gray_img)
plt.figure(figsize=(10,4))
plt.subplot(1,2,1)
plt.imshow(gray_img, cmap="gray")
plt.title("Orijinal")
plt.axis("off")
plt.subplot(1,2,2)
plt.imshow(equalized, cmap="gray")
plt.title("Histogram Equalization")
plt.axis("off")
plt.show()

_, thresh = cv2.threshold(gray_img, 127, 255, cv2.THRESH_BINARY)
plt.imshow(thresh, cmap="gray")
plt.title("Binary Threshold")
plt.axis("off")
plt.show()

kernel = np.ones((3,3), np.uint8)
erosion = cv2.erode(thresh, kernel, iterations=1)
plt.imshow(erosion, cmap="gray")
plt.title("Erosion")
plt.axis("off")
plt.show()

dilation = cv2.dilate(thresh, kernel, iterations=1)
plt.imshow(dilation, cmap="gray")
plt.title("Dilation")
plt.axis("off")
plt.show()

import numpy as np
import cv2
import matplotlib.pyplot as plt
from matplotlib.gridspec import GridSpec

# ---------------- Aktivasyon Fonksiyonları ----------------
def relu(x):
    return np.maximum(0, x)

def leaky_relu(x, alpha=0.01):
    return np.where(x > 0, x, alpha * x)

def sigmoid(x):
    return 1 / (1 + np.exp(-np.clip(x, -500, 500)))

def tanh(x):
    return np.tanh(x)

def softmax(x):
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum()

# ---------------- Konvolüsyon Fonksiyonu ----------------
def conv2d_numpy(image, kernel, padding=0):
    if padding > 0:
        image = np.pad(
            image,
            ((padding, padding), (padding, padding)),
            mode='constant'
        )

    kh, kw = kernel.shape
    h, w = image.shape

    output = np.zeros((h - kh + 1, w - kw + 1))

    for i in range(output.shape[0]):
        for j in range(output.shape[1]):
            region = image[i:i + kh, j:j + kw]
            output[i, j] = np.sum(region * kernel)

    return output

# ---------------- Test Görüntüsü ----------------
# X daha önce oluşturulmuş olmalı: örn. X.shape = (adet, 64, 64, 3)
test_img = (X[0] * 255).astype(np.uint8)

test_img_gray = cv2.cvtColor(test_img, cv2.COLOR_RGB2GRAY)

# 64x64 olduğu için küçük bir bölge seçiyoruz
test_slice = test_img_gray[10:50, 10:50]

sobel_kernel = np.array([
    [-1, 0, 1],
    [-2, 0, 2],
    [-1, 0, 1]
]) / 4.0

sobel_out = conv2d_numpy(
    test_slice,
    sobel_kernel,
    padding=1
)

relu_out = relu(sobel_out)

# ---------------- Aktivasyon Grafikleri ----------------
x = np.linspace(-4, 4, 400)

fig = plt.figure(figsize=(18, 9))
gs = GridSpec(2, 5, figure=fig, hspace=0.4, wspace=0.35)

activations = [
    ('ReLU', relu(x), 'crimson'),
    ('Leaky ReLU', leaky_relu(x), 'orange'),
    ('Sigmoid', sigmoid(x), 'steelblue'),
    ('Tanh', tanh(x), 'green')
]

for i, (name, y_act, color) in enumerate(activations):
    ax = fig.add_subplot(gs[0, i])

    ax.plot(x, y_act, color=color, linewidth=2.5)
    ax.axhline(0, color='gray')
    ax.axvline(0, color='gray')

    ax.set_title(name, fontweight='bold')
    ax.grid(True, alpha=0.3)

# ---------------- Softmax ----------------
ax_sm = fig.add_subplot(gs[0, 4])

logits = np.array([2.0, 1.0, 0.1])
probs = softmax(logits)

bars = ax_sm.bar(
    ['Sınıf 0', 'Sınıf 1', 'Sınıf 2'],
    probs
)

for bar, p in zip(bars, probs):
    ax_sm.text(
        bar.get_x() + bar.get_width() / 2,
        bar.get_height() + 0.02,
        f'{p:.2f}',
        ha='center'
    )

ax_sm.set_title("Softmax", fontweight='bold')
ax_sm.set_ylim(0, 0.8)

# ---------------- ReLU Görselleştirmesi ----------------
ax_raw = fig.add_subplot(gs[1, 0:2])
ax_relu = fig.add_subplot(gs[1, 2:4])
ax_hist = fig.add_subplot(gs[1, 4])

ax_raw.imshow(sobel_out, cmap='seismic')
ax_raw.set_title("Sobel Çıkışı")
ax_raw.axis('off')

ax_relu.imshow(relu_out, cmap='hot')
ax_relu.set_title("ReLU Sonrası")
ax_relu.axis('off')

ax_hist.hist(
    sobel_out.flatten(),
    bins=40,
    alpha=0.6,
    label='Önce'
)

ax_hist.hist(
    relu_out.flatten(),
    bins=40,
    alpha=0.6,
    label='Sonra'
)

ax_hist.set_title("Değer Dağılımı")
ax_hist.legend()

plt.suptitle(
    "Aktivasyon Fonksiyonları ve ReLU Örneği",
    fontsize=14,
    fontweight='bold'
)

plt.show()

# ==========================
# MLP MİMARİ DERİNLİĞİ KARŞILAŞTIRMA
# ==========================

import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score

# PCA'dan gelen özellikleri kullanıyoruz
# X_pca shape örnek: (1200, 50)
X_features = X_pca

# Train-test ayırma
X_train, X_test, y_train, y_test = train_test_split(
    X_features,
    y,
    test_size=0.25,
    random_state=42,
    stratify=y
)

# Ölçekleme
scaler = StandardScaler()
X_train_sc = scaler.fit_transform(X_train)
X_test_sc = scaler.transform(X_test)

# Farklı MLP mimarileri
architectures = {
    'Yüzeysel\n(1 katman)': (64,),
    'Orta\n(2 katman)': (128, 64),
    'Derin\n(3 katman)': (256, 128, 64),
    'Çok Derin\n(4 katman)': (512, 256, 128, 64),
}

results_arch = {}

for arch_name, layers in architectures.items():

    mlp = MLPClassifier(
        hidden_layer_sizes=layers,
        activation='relu',
        solver='adam',
        alpha=1e-4,
        max_iter=200,
        random_state=42,
        early_stopping=True,
        validation_fraction=0.1
    )

    mlp.fit(X_train_sc, y_train)

    train_acc = accuracy_score(y_train, mlp.predict(X_train_sc))
    test_acc = accuracy_score(y_test, mlp.predict(X_test_sc))

    n_params = (
        sum(w.size for w in mlp.coefs_) +
        sum(b.size for b in mlp.intercepts_)
    )

    results_arch[arch_name] = {
        'model': mlp,
        'train_acc': train_acc,
        'test_acc': test_acc,
        'n_iter': mlp.n_iter_,
        'n_params': n_params,
        'loss_curve': mlp.loss_curve_
    }

    print(
        f"{arch_name.replace(chr(10), ' '):<25} | "
        f"Eğitim: {train_acc * 100:.1f}%  "
        f"Test: {test_acc * 100:.1f}%  "
        f"Parametre: {n_params:,}  "
        f"İterasyon: {mlp.n_iter_}"
    )

# ==========================
# Grafikler
# ==========================

fig, axes = plt.subplots(1, 2, figsize=(16, 6))

colors_arch = ['#e74c3c', '#3498db', '#2ecc71', '#f39c12']

# Loss eğrileri
for (name, res), color in zip(results_arch.items(), colors_arch):
    axes[0].plot(
        res['loss_curve'],
        color=color,
        linewidth=2,
        label=f"{name.replace(chr(10), ' ')} ({res['n_iter']} iter)"
    )

axes[0].set_xlabel("İterasyon")
axes[0].set_ylabel("Kayıp (Loss)")
axes[0].set_title("Eğitim Kayıp Eğrileri", fontweight='bold')
axes[0].legend(fontsize=9)
axes[0].set_yscale('log')
axes[0].grid(True, alpha=0.3)

# Accuracy bar grafiği
x_pos = np.arange(len(results_arch))

tr_accs = [r['train_acc'] * 100 for r in results_arch.values()]
te_accs = [r['test_acc'] * 100 for r in results_arch.values()]

bar_w = 0.35

bars1 = axes[1].bar(
    x_pos - bar_w / 2,
    tr_accs,
    bar_w,
    label='Eğitim',
    alpha=0.8
)

bars2 = axes[1].bar(
    x_pos + bar_w / 2,
    te_accs,
    bar_w,
    label='Test',
    alpha=0.8
)

for bar, val in zip(list(bars1) + list(bars2), tr_accs + te_accs):
    axes[1].text(
        bar.get_x() + bar.get_width() / 2,
        bar.get_height() + 0.3,
        f'{val:.1f}%',
        ha='center',
        va='bottom',
        fontsize=8,
        fontweight='bold'
    )

axes[1].set_xticks(x_pos)
axes[1].set_xticklabels(results_arch.keys(), fontsize=9)
axes[1].set_ylabel("Doğruluk (%)")
axes[1].set_title("Mimari Derinliği vs Doğruluk", fontweight='bold')
axes[1].legend()
axes[1].grid(True, alpha=0.3, axis='y')

plt.tight_layout()
plt.show()

import os
import cv2
import numpy as np
from collections import Counter

base_path = "/content/seg_train/seg_train"  # sende klasör yolu buysa

IMG_SIZE = 64
MAX_PER_CLASS = 200

X = []
y = []
class_names = []

for label, class_name in enumerate(sorted(os.listdir(base_path))):
    class_path = os.path.join(base_path, class_name)

    if not os.path.isdir(class_path):
        continue

    class_names.append(class_name)

    count = 0
    for img_name in os.listdir(class_path):
        if count >= MAX_PER_CLASS:
            break

        img_path = os.path.join(class_path, img_name)

        img = cv2.imread(img_path)
        if img is None:
            continue

        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))

        X.append(img / 255.0)
        y.append(label)

        count += 1

X = np.array(X)
y = np.array(y)

print("Sınıflar:", class_names)
print("X shape:", X.shape)
print("y shape:", y.shape)
print("Sınıf dağılımı:", Counter(y))

from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import numpy as np

# Görselleri 1 boyuta indiriyoruz
X_flat = X.reshape(X.shape[0], -1)

print("X_flat shape:", X_flat.shape)

# Ölçekleme
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_flat)

# PCA
pca = PCA(n_components=50, random_state=42)
X_pca = pca.fit_transform(X_scaled)

print("X_pca shape:", X_pca.shape)
print("Açıklanan varyans oranı:", pca.explained_variance_ratio_.sum())

import numpy as np
import matplotlib.pyplot as plt
import time

from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier

X_features = X_pca

cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

pipelines = {
    "KNN": Pipeline([
        ("scaler", StandardScaler()),
        ("model", KNeighborsClassifier(n_neighbors=5, weights="distance"))
    ]),

    "SVM": Pipeline([
        ("scaler", StandardScaler()),
        ("model", SVC(kernel="rbf", C=10, gamma="scale"))
    ]),

    "MLP": Pipeline([
        ("scaler", StandardScaler()),
        ("model", MLPClassifier(
            hidden_layer_sizes=(256, 128),
            max_iter=300,
            random_state=42,
            early_stopping=True
        ))
    ])
}

cv_results = {}

print("5-Fold Cross Validation başlıyor...\n")
print(f"{'Model':<10} {'Ortalama':>10} {'Std':>10} {'Süre':>10}")
print("-" * 45)

for name, pipe in pipelines.items():
    start = time.time()

    scores = cross_val_score(
        pipe,
        X_features,
        y,
        cv=cv,
        scoring="accuracy",
        n_jobs=-1
    )

    elapsed = time.time() - start

    cv_results[name] = {
        "scores": scores,
        "mean": scores.mean(),
        "std": scores.std(),
        "time": elapsed
    }

    print(
        f"{name:<10} "
        f"{scores.mean()*100:>9.2f}% "
        f"{scores.std()*100:>9.2f}% "
        f"{elapsed:>9.1f}s"
    )

# Grafikler
names = list(cv_results.keys())
means = [cv_results[n]["mean"] * 100 for n in names]
stds = [cv_results[n]["std"] * 100 for n in names]
times = [cv_results[n]["time"] for n in names]

fig, axes = plt.subplots(1, 3, figsize=(18, 6))

# 1. Accuracy bar plot
bars = axes[0].bar(names, means, alpha=0.85)
axes[0].errorbar(names, means, yerr=stds, fmt="none", color="black", capsize=5)

for bar, m, s in zip(bars, means, stds):
    axes[0].text(
        bar.get_x() + bar.get_width() / 2,
        m + 0.5,
        f"{m:.1f}%\n±{s:.1f}",
        ha="center",
        fontsize=9
    )

axes[0].set_title("5-Fold CV Doğruluk")
axes[0].set_ylabel("Doğruluk (%)")
axes[0].grid(True, alpha=0.3, axis="y")

# 2. Fold dağılımı
all_scores = [cv_results[n]["scores"] * 100 for n in names]
axes[1].boxplot(all_scores, labels=names)
axes[1].set_title("Fold Skor Dağılımı")
axes[1].set_ylabel("Doğruluk (%)")
axes[1].grid(True, alpha=0.3, axis="y")

# 3. Accuracy vs time
for name, mean, t in zip(names, means, times):
    axes[2].scatter(t, mean, s=250, label=name)
    axes[2].annotate(name, (t, mean), xytext=(5, 5), textcoords="offset points")

axes[2].set_title("Doğruluk - Süre Karşılaştırması")
axes[2].set_xlabel("Süre (saniye)")
axes[2].set_ylabel("Doğruluk (%)")
axes[2].grid(True, alpha=0.3)
axes[2].legend()

plt.suptitle("Model Karşılaştırması: KNN - SVM - MLP", fontsize=14, fontweight="bold")
plt.tight_layout()
plt.show()

# ==========================
# SALIENCY MAP - MODEL HANGİ BÖLGEYE BAKIYOR?
# ==========================

import numpy as np
import cv2
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

# --------------------------
# 1. Gri görüntü verisi hazırla
# --------------------------

X_gray = []

for img in X:
    img_uint8 = (img * 255).astype(np.uint8)
    gray = cv2.cvtColor(img_uint8, cv2.COLOR_RGB2GRAY)
    gray = gray / 255.0
    X_gray.append(gray)

X_gray = np.array(X_gray)
X_gray_flat = X_gray.reshape(X_gray.shape[0], -1)

print("Gri görüntü shape:", X_gray.shape)
print("Flatten shape:", X_gray_flat.shape)

# class_names yoksa otomatik oluştur
try:
    classes = class_names
except NameError:
    classes = [f"Sınıf {i}" for i in sorted(np.unique(y))]

print("Sınıflar:", classes)

# --------------------------
# 2. Train-test ayır
# --------------------------

X_train_g, X_test_g, y_train_g, y_test_g = train_test_split(
    X_gray_flat,
    y,
    test_size=0.25,
    random_state=42,
    stratify=y
)

# --------------------------
# 3. SVM modeli eğit
# --------------------------

best_model = Pipeline([
    ("scaler", StandardScaler()),
    ("clf", SVC(
        kernel="rbf",
        C=10,
        gamma="scale",
        probability=True,
        random_state=42
    ))
])

best_model.fit(X_train_g, y_train_g)

print("Model eğitildi.")
print("Test doğruluğu:", best_model.score(X_test_g, y_test_g))

# --------------------------
# 4. Perturbation tabanlı saliency map
# --------------------------

def saliency_map_perturbation(model, image_flat, target_class, img_size=64, step=4):
    """
    Görüntü üzerinde küçük blokları sırayla kapatır.
    Hangi blok kapatılınca modelin güveni düşüyorsa, o bölge önemlidir.
    """

    base_prob = model.predict_proba([image_flat])[0][target_class]

    saliency = np.zeros((img_size, img_size))
    image_2d = image_flat.reshape(img_size, img_size)

    for r in range(0, img_size, step):
        for c in range(0, img_size, step):

            perturbed = image_2d.copy()
            perturbed[r:r + step, c:c + step] = 0

            perturbed_flat = perturbed.reshape(1, -1)

            perturbed_prob = model.predict_proba(perturbed_flat)[0][target_class]

            importance = base_prob - perturbed_prob

            saliency[r:r + step, c:c + step] = importance

    return saliency


# --------------------------
# 5. Her sınıftan bir örnek göster
# --------------------------

num_classes = len(classes)

fig, axes = plt.subplots(3, num_classes, figsize=(3 * num_classes, 9))

if num_classes == 1:
    axes = axes.reshape(3, 1)

for col, class_name in enumerate(classes):

    candidates = np.where(y_test_g == col)[0]

    if len(candidates) == 0:
        continue

    idx = candidates[0]

    img_flat = X_test_g[idx]
    img_2d = img_flat.reshape(64, 64)

    pred_class = best_model.predict([img_flat])[0]
    pred_prob = best_model.predict_proba([img_flat])[0]

    sal_map = saliency_map_perturbation(
        best_model,
        img_flat,
        target_class=pred_class,
        img_size=64,
        step=4
    )

    sal_clipped = np.clip(sal_map, 0, None)

    # Orijinal görüntü
    axes[0, col].imshow(img_2d, cmap="gray")
    axes[0, col].set_title(
        f"Gerçek: {class_name}\nTahmin: {classes[pred_class]} ({pred_prob[pred_class] * 100:.0f}%)",
        fontsize=8,
        fontweight="bold",
        color="green" if pred_class == col else "red"
    )
    axes[0, col].axis("off")

    # Saliency map
    axes[1, col].imshow(sal_clipped, cmap="hot")
    axes[1, col].set_title("Saliency Map", fontsize=8)
    axes[1, col].axis("off")

    # Overlay
    img_norm = (img_2d - img_2d.min()) / (img_2d.max() - img_2d.min() + 1e-8)
    sal_norm = (sal_clipped - sal_clipped.min()) / (sal_clipped.max() - sal_clipped.min() + 1e-8)

    overlay = np.stack([img_norm] * 3, axis=-1)

    overlay[:, :, 0] = np.clip(img_norm + sal_norm * 0.8, 0, 1)
    overlay[:, :, 1] = np.clip(img_norm - sal_norm * 0.3, 0, 1)
    overlay[:, :, 2] = np.clip(img_norm - sal_norm * 0.3, 0, 1)

    axes[2, col].imshow(overlay)
    axes[2, col].set_title("Overlay", fontsize=8)
    axes[2, col].axis("off")

axes[0, 0].set_ylabel("Orijinal", fontsize=11, fontweight="bold")
axes[1, 0].set_ylabel("Saliency", fontsize=11, fontweight="bold")
axes[2, 0].set_ylabel("Overlay", fontsize=11, fontweight="bold")

plt.suptitle(
    "Saliency Map — Model Görüntünün Hangi Bölgelerine Bakıyor?",
    fontsize=14,
    fontweight="bold"
)

plt.tight_layout()
plt.show()

# ==========================
# SAF NUMPY CNN - FORWARD PASS
# ==========================

import numpy as np
import cv2

def conv2d_numpy(image, kernel, padding=0):
    if padding > 0:
        image = np.pad(
            image,
            ((padding, padding), (padding, padding)),
            mode="constant"
        )

    kh, kw = kernel.shape
    h, w = image.shape

    output = np.zeros((h - kh + 1, w - kw + 1))

    for i in range(output.shape[0]):
        for j in range(output.shape[1]):
            region = image[i:i + kh, j:j + kw]
            output[i, j] = np.sum(region * kernel)

    return output


class SimpleCNN:
    """
    Saf NumPy CNN — Forward Pass
    Input 64x64
    Conv 3x3
    ReLU
    MaxPool 2x2
    Flatten
    Dense
    Softmax
    """

    def __init__(self, n_filters=4, input_size=64, n_classes=6, seed=42):
        rng = np.random.default_rng(seed)

        self.n_filters = n_filters
        self.input_size = input_size
        self.n_classes = n_classes

        self.conv_kernels = rng.standard_normal((n_filters, 3, 3)) * 0.1
        self.conv_biases = np.zeros(n_filters)

        pooled_h = input_size // 2
        pooled_w = input_size // 2
        flat_size = n_filters * pooled_h * pooled_w

        self.dense_W = rng.standard_normal((flat_size, n_classes)) * 0.1
        self.dense_b = np.zeros(n_classes)

        self.activations = {}

    def conv_layer(self, image):
        feature_maps = []

        for i, kernel in enumerate(self.conv_kernels):
            fm = conv2d_numpy(image, kernel, padding=1)
            fm = fm + self.conv_biases[i]
            feature_maps.append(fm)

        return np.stack(feature_maps, axis=0)

    def relu_layer(self, x):
        return np.maximum(0, x)

    def max_pool(self, feature_maps, pool_size=2, stride=2):
        n, h, w = feature_maps.shape

        h_out = h // stride
        w_out = w // stride

        pooled = np.zeros((n, h_out, w_out))

        for f in range(n):
            for i in range(h_out):
                for j in range(w_out):
                    r0 = i * stride
                    r1 = r0 + pool_size
                    c0 = j * stride
                    c1 = c0 + pool_size

                    pooled[f, i, j] = feature_maps[f, r0:r1, c0:c1].max()

        return pooled

    def dense_layer(self, flat_input):
        return flat_input @ self.dense_W + self.dense_b

    def softmax(self, logits):
        e = np.exp(logits - np.max(logits))
        return e / np.sum(e)

    def forward(self, image):
        self.activations["input"] = image

        conv_out = self.conv_layer(image)
        self.activations["conv"] = conv_out

        relu_out = self.relu_layer(conv_out)
        self.activations["relu"] = relu_out

        pool_out = self.max_pool(relu_out)
        self.activations["pool"] = pool_out

        flat_out = pool_out.flatten()
        self.activations["flat"] = flat_out

        dense_out = self.dense_layer(flat_out)
        self.activations["dense"] = dense_out

        probs = self.softmax(dense_out)
        self.activations["output"] = probs

        return probs


# --------------------------
# CNN'i bir görüntü üzerinde çalıştır
# --------------------------

try:
    classes = class_names
except NameError:
    classes = [f"Sınıf {i}" for i in sorted(np.unique(y))]

sample_rgb = (X[0] * 255).astype(np.uint8)
sample_gray = cv2.cvtColor(sample_rgb, cv2.COLOR_RGB2GRAY)
sample = sample_gray / 255.0

cnn = SimpleCNN(
    n_filters=4,
    input_size=64,
    n_classes=len(classes)
)

probs = cnn.forward(sample)

print("=" * 60)
print(f"Giriş boyutu        : {sample.shape}")
print(f"Conv çıkışı         : {cnn.activations['conv'].shape}")
print(f"ReLU çıkışı         : {cnn.activations['relu'].shape}")
print(f"MaxPool çıkışı      : {cnn.activations['pool'].shape}")
print(f"Flatten çıkışı      : {cnn.activations['flat'].shape}")
print(f"Dense çıkışı        : {cnn.activations['dense'].shape}")
print(f"Softmax çıkışı      : {cnn.activations['output'].shape}  toplam={probs.sum():.4f}")
print("=" * 60)

true_label = int(y[0])
pred_label = int(np.argmax(probs))

print(f"\nGerçek etiket: {classes[true_label]}")
print(f"Model tahmini: {classes[pred_label]}  olasılık: {probs.max():.3f}")

print("\nTüm sınıf olasılıkları:")

for i, p in enumerate(probs):
    bar = "█" * int(p * 40)
    print(f"{classes[i]:<12}: {p:.4f}  {bar}")

# ==========================
# CNN ÖZELLİK HARİTALARINI GÖRSELLEŞTİRME
# ==========================

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.gridspec import GridSpec

# classes yoksa oluştur
try:
    classes = class_names
except NameError:
    classes = [f"Sınıf {i}" for i in sorted(np.unique(y))]

fig = plt.figure(figsize=(20, 14))
gs = GridSpec(4, 7, figure=fig, hspace=0.5, wspace=0.3)

# --------------------------
# Satır 0: Giriş görüntüsü
# --------------------------

ax0 = fig.add_subplot(gs[0, :2])
ax0.imshow(sample, cmap="gray", interpolation="nearest")
ax0.set_title(
    f"Giriş Görüntüsü (64x64)\nSınıf: {classes[int(y[0])]}",
    fontweight="bold",
    fontsize=11
)
ax0.axis("off")

# --------------------------
# Satır 0: Kernel görüntüleri
# --------------------------

for f in range(cnn.n_filters):
    ax = fig.add_subplot(gs[0, 2 + f])
    ax.imshow(cnn.conv_kernels[f], cmap="RdBu_r", vmin=-0.3, vmax=0.3)

    for ki in range(3):
        for kj in range(3):
            ax.text(
                kj,
                ki,
                f"{cnn.conv_kernels[f][ki, kj]:.2f}",
                ha="center",
                va="center",
                fontsize=7
            )

    ax.set_title(f"Filtre {f + 1}\n3x3 Kernel", fontsize=9)
    ax.axis("off")

fig.text(
    0.02,
    0.78,
    "Giriş &\nKerneller",
    fontsize=10,
    fontweight="bold",
    va="center"
)

# --------------------------
# Satır 1: Conv çıkışı
# --------------------------

fig.text(
    0.02,
    0.58,
    "Conv\nHam",
    fontsize=10,
    fontweight="bold",
    va="center"
)

for f in range(cnn.n_filters):
    ax = fig.add_subplot(gs[1, f])
    fm = cnn.activations["conv"][f]
    vmax = np.abs(fm).max()

    ax.imshow(
        fm,
        cmap="seismic",
        vmin=-vmax,
        vmax=vmax
    )

    ax.set_title(
        f"Filtre {f + 1} Çıkışı\n64x64 Negatif+Pozitif",
        fontsize=8
    )
    ax.axis("off")

# --------------------------
# Satır 2: ReLU çıkışı
# --------------------------

fig.text(
    0.02,
    0.38,
    "ReLU\nSonrası",
    fontsize=10,
    fontweight="bold",
    va="center"
)

for f in range(cnn.n_filters):
    ax = fig.add_subplot(gs[2, f])
    fm = cnn.activations["relu"][f]
    active = (fm > 0).sum()

    ax.imshow(fm, cmap="hot")

    ax.set_title(
        f"Filtre {f + 1} ReLU\n{active}/{fm.size} aktif nöron",
        fontsize=8
    )
    ax.axis("off")

# --------------------------
# Satır 3: MaxPool çıkışı
# --------------------------

fig.text(
    0.02,
    0.16,
    "MaxPool\n& Çıkış",
    fontsize=10,
    fontweight="bold",
    va="center"
)

for f in range(cnn.n_filters):
    ax = fig.add_subplot(gs[3, f])
    fm = cnn.activations["pool"][f]

    ax.imshow(
        fm,
        cmap="hot",
        interpolation="nearest"
    )

    ax.set_title(
        f"Filtre {f + 1} Pool\n{fm.shape[0]}x{fm.shape[1]} özellik",
        fontsize=8
    )
    ax.axis("off")

# --------------------------
# Softmax çıkışı
# --------------------------

ax_out = fig.add_subplot(gs[3, 4:])

pred_idx = int(np.argmax(probs))

colors_bar = [
    "#e74c3c" if i == pred_idx else "#3498db"
    for i in range(len(classes))
]

ax_out.barh(
    range(len(classes)),
    probs,
    color=colors_bar,
    alpha=0.8
)

ax_out.set_yticks(range(len(classes)))
ax_out.set_yticklabels(classes)
ax_out.set_xlabel("Olasılık")
ax_out.set_title(
    f"Softmax Çıkışı\nTahmin: {classes[pred_idx]}",
    fontweight="bold"
)

ax_out.axvline(
    x=1 / len(classes),
    color="gray",
    linestyle="--",
    alpha=0.5,
    label=f"Rastgele ({100 / len(classes):.1f}%)"
)

ax_out.grid(True, alpha=0.3, axis="x")
ax_out.legend()

plt.suptitle(
    "CNN İleri Yayılım — Her Katmanın Özellik Haritaları\n"
    "Conv → ReLU → MaxPool → Dense → Softmax",
    fontsize=14,
    fontweight="bold"
)

plt.show()

