# -*- coding: utf-8 -*-
"""python_temel_quiz.ipynb adlı not defterinin kopyası

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E6GqpxaC3WKURycAi1aVD4Vax9X5hsuf

# 🐍 Python Temel Komutlar — Quiz

Bu notebook; **değişkenler, veri tipleri, koşullar, döngüler, fonksiyonlar, listeler, sözlükler ve hata yönetimi** konularını kapsayan 5 sorudan oluşmaktadır.

Her soruyu okuyun, `# KODUNUZU BURAYA YAZIN` yazan hücreye cevabınızı girin, ardından **Cevap** hücresini açarak kontrol edin.

---

## Soru 1 — Değişkenler, Veri Tipleri ve String İşlemleri

Aşağıdaki bilgileri kullanarak bir **kişi kartı** oluşturun:

- `isim = "ahmet yılmaz"` → baş harfleri büyük yapın (`title()`)
- `dogum_yili = 1998` → 2025 yılına göre yaşı hesaplayın
- `boy = 1.75` (metre cinsinden)
- `aktif = True`

**Görev:** Aşağıdaki çıktıyı üretecek kodu yazın:

```
=== KİŞİ KARTI ===
İsim   : Ahmet Yılmaz
Yaş    : 27
Boy    : 1.75 m
Durum  : Aktif
```

> 💡 İpucu: f-string ve `title()` kullanın. Durum için ternary if ile `"Aktif"` / `"Pasif"` yazdırın.
"""

# KODUNUZU BURAYA YAZIN
isim = "ahmet yilmaz"
dogum_yili = 1998
boy = 1.75
aktif = True

yas = 2025 - dogum_yili

durum = "Aktif" if aktif else "Pasif"

print("=== KİŞİ KARTI ===")
print(f"İsim  : {isim.title()}")
print(f"Yaş   : {yas}")
print(f"Boy   : {boy} m")
print(f"Durum : {durum}")

"""<details>
<summary>✅ Cevabı Görmek İçin Tıklayın</summary>

```python
isim = "ahmet yılmaz"
dogum_yili = 1998
boy = 1.75
aktif = True

yas = 2025 - dogum_yili
durum = "Aktif" if aktif else "Pasif"

print("=== KİŞİ KARTI ===")
print(f"İsim   : {isim.title()}")
print(f"Yaş    : {yas}")
print(f"Boy    : {boy} m")
print(f"Durum  : {durum}")
```

**Konu:** Değişkenler · String metodları (`title()`) · f-string · Ternary if · Tip dönüşümü
</details>

---
## Soru 2 — Koşullar ve Operatörler

Bir market uygulaması için **indirim hesaplayıcı** yazın:

| Toplam Tutar | İndirim Oranı |
|---|---|
| 500 TL ve üzeri | %20 |
| 200 TL ve üzeri | %10 |
| 100 TL ve üzeri | %5 |
| 100 TL altı | İndirim yok |

**Görev:** `tutar` değişkenini alıp indirim sonrası ödenmesi gereken tutarı yazdıran kodu yazın.

```
# tutar = 350 için beklenen çıktı:
Tutar    : 350 TL
İndirim  : %10 (35.0 TL)
Ödenecek : 315.0 TL
```

> 💡 İpucu: `if / elif / else` kullanın.
"""

# KODUNUZU BURAYA YAZIN
tutar = 350

if tutar >= 500:
    indirim_orani = 20
elif tutar >= 200:
    indirim_orani = 10
elif tutar >= 100:
    indirim_orani = 5
else:
    indirim_orani = 0

indirim_miktari = tut

"""<details>
<summary>✅ Cevabı Görmek İçin Tıklayın</summary>

```python
tutar = 350

if tutar >= 500:
    oran = 20
elif tutar >= 200:
    oran = 10
elif tutar >= 100:
    oran = 5
else:
    oran = 0

indirim_miktari = tutar * oran / 100
odenecek = tutar - indirim_miktari

if oran > 0:
    print(f"Tutar    : {tutar} TL")
    print(f"İndirim  : %{oran} ({indirim_miktari} TL)")
    print(f"Ödenecek : {odenecek} TL")
else:
    print(f"İndirim yok. Ödenecek: {tutar} TL")
```

**Konu:** if / elif / else · Karşılaştırma operatörleri · Aritmetik operatörler
</details>

---
## Soru 3 — Döngüler ve Listeler

Aşağıdaki öğrenci notları listesi verilmiştir:

```python
notlar = [72, 45, 88, 91, 55, 63, 78, 40, 95, 60]
```

**Görev:** Tek bir döngü kullanarak şunları hesaplayın ve yazdırın:

1. Geçen öğrenci sayısı (50 ve üzeri)
2. Kalan öğrenci sayısı (50 altı)
3. En yüksek not
4. Notların ortalaması
5. 80 ve üzeri not alan öğrencilerin notlarından oluşan yeni liste

```
# Beklenen çıktı:
Geçen    : 8 öğrenci
Kalan    : 2 öğrenci
En yüksek: 95
Ortalama : 68.7
Yüksek notlar: [88, 91, 95]
```

> 💡 İpucu: `for` döngüsü + sayaç değişkenleri kullanın. Son madde için liste comprehension deneyin.
"""

notlar = [72, 45, 88, 91, 55, 63, 78, 40, 95, 60]

# KODUNUZU BURAYA YAZIN
gecen = 0
kalan = 0
en_yuksek = notlar[0]
toplam = 0

for not_ in notlar:
    toplam += not_
    if not_ >= 50:
        gecen += 1
    else:
        kalan += 1
    if not_ > en_yuksek:
        en_yuksek = not_

ortalama = round(toplam / len(notlar), 1)
yuksek_notlar = [n for n in notlar if n >= 80]
print(f"Geçen    : {gecen} öğrenci")
print(f"Kalan    : {kalan} öğrenci")
print(f"En yüksek: {en_yuksek}")
print(f"Ortalama : {ortalama}")
print(f"Yüksek notlar: {yuksek_notlar}")

"""<details>
<summary>✅ Cevabı Görmek İçin Tıklayın</summary>

```python
notlar = [72, 45, 88, 91, 55, 63, 78, 40, 95, 60]

gecen = 0
kalan = 0
en_yuksek = notlar[0]
toplam = 0

for not_ in notlar:
    toplam += not_
    if not_ >= 50:
        gecen += 1
    else:
        kalan += 1
    if not_ > en_yuksek:
        en_yuksek = not_

ortalama = round(toplam / len(notlar), 1)
yuksek_notlar = [n for n in notlar if n >= 80]

print(f"Geçen    : {gecen} öğrenci")
print(f"Kalan    : {kalan} öğrenci")
print(f"En yüksek: {en_yuksek}")
print(f"Ortalama : {ortalama}")
print(f"Yüksek notlar: {yuksek_notlar}")
```

**Konu:** for döngüsü · Sayaç değişkenleri · Liste comprehension · round()
</details>

---
## Soru 4 — Fonksiyonlar ve Sözlükler

Bir **kelime frekans sayacı** fonksiyonu yazın.

Fonksiyon bir cümle alıp her kelimenin kaç kez geçtiğini sözlük olarak döndürsün.

```python
cumle = "python öğren python sev python kullan ve python ile kod yaz"
```

**Beklenen çıktı:**
```
{'python': 4, 'öğren': 1, 'sev': 1, 'kullan': 1, 've': 1, 'ile': 1, 'kod': 1, 'yaz': 1}
En çok geçen kelime: 'python' (4 kez)
Toplam farklı kelime: 8
```

> 💡 İpucu: `split()` ile kelimelere böl. Sözlüğe eklerken `dict.get(kelime, 0)` kullan.
"""

cumle = "python öğren python sev python kullan ve python ile kod yaz"

# KODUNUZU BURAYA YAZIN
# def kelime_say(cumle): ...
def kelime_say(cumle):
    frekans = {}
    for kelime in cumle.split():
        frekans[kelime] = frekans.get(kelime, 0) + 1
    return frekans

sonuc = kelime_say(cumle)
en_cok = max(sonuc, key=sonuc.get)

print(sonuc)
print(f"En çok geçen kelime: '{en_cok}' ({sonuc[en_cok]} kez)")
print(f"Toplam farklı kelime: {len(sonuc)}")

"""<details>
<summary>✅ Cevabı Görmek İçin Tıklayın</summary>

```python
cumle = "python öğren python sev python kullan ve python ile kod yaz"

def kelime_say(cumle):
    frekans = {}
    for kelime in cumle.split():
        frekans[kelime] = frekans.get(kelime, 0) + 1
    return frekans

sonuc = kelime_say(cumle)
en_cok = max(sonuc, key=sonuc.get)

print(sonuc)
print(f"En çok geçen kelime: '{en_cok}' ({sonuc[en_cok]} kez)")
print(f"Toplam farklı kelime: {len(sonuc)}")
```

**Konu:** Fonksiyon tanımlama · Sözlük işlemleri · `split()` · `max()` + `key` parametresi
</details>

---
## Soru 5 — Hata Yönetimi (try / except)

Aşağıdaki `guvenli_hesap` fonksiyonunu tamamlayın.

Fonksiyon iki parametre alsın: `sayi` (string olarak gelecek) ve `bolen` (string olarak gelecek).

Olası hatalar:
- `sayi` veya `bolen` sayıya çevrilemezse → `"Hata: Geçersiz sayı"` yazdır
- `bolen` sıfırsa → `"Hata: Sıfıra bölünemez"` yazdır
- Hata yoksa → sonucu yazdır
- Her durumda → `"İşlem tamamlandı."` yazdır

```python
# Test senaryoları:
guvenli_hesap("10", "2")      # Sonuç: 5.0  →  İşlem tamamlandı.
guvenli_hesap("10", "0")      # Hata: Sıfıra bölünemez  →  İşlem tamamlandı.
guvenli_hesap("abc", "2")     # Hata: Geçersiz sayı  →  İşlem tamamlandı.
```

> 💡 İpucu: `try / except ValueError / except ZeroDivisionError / finally` kullanın.
"""

def guvenli_hesap(sayi, bolen):
    # KODUNUZU BURAYA YAZIN
    pass

# Test et:
guvenli_hesap("10", "2")
print("---")
guvenli_hesap("10", "0")
print("---")
guvenli_hesap("abc", "2")

"""<details>
<summary>✅ Cevabı Görmek İçin Tıklayın</summary>

```python
def guvenli_hesap(sayi, bolen):
    try:
        a = float(sayi)
        b = float(bolen)
        sonuc = a / b
    except ValueError:
        print("Hata: Geçersiz sayı")
    except ZeroDivisionError:
        print("Hata: Sıfıra bölünemez")
    else:
        print(f"Sonuç: {sonuc}")
    finally:
        print("İşlem tamamlandı.")

guvenli_hesap("10", "2")
print("---")
guvenli_hesap("10", "0")
print("---")
guvenli_hesap("abc", "2")
```

**Konu:** try / except / else / finally · ValueError · ZeroDivisionError · float()
</details>

---
## 📊 Konu Özeti

| Soru | Kapsanan Konular |
|------|------------------|
| Soru 1 | Değişkenler, veri tipleri, string metodları, f-string, ternary if |
| Soru 2 | if / elif / else, karşılaştırma ve aritmetik operatörler |
| Soru 3 | for döngüsü, listeler, liste comprehension, sayaç mantığı |
| Soru 4 | Fonksiyonlar, sözlükler, split(), max() |
| Soru 5 | try / except / else / finally, hata yönetimi |
"""